//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeIssueDetail
    {
        public int EfollowId { get; set; }
        public Nullable<int> statusid { get; set; }
        public string Remark { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string issueid { get; set; }
    }
}
