//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Innovation_Management_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Innovation_Management_User()
        {
            this.Leave_Management_Approval_Matrix = new HashSet<Leave_Management_Approval_Matrix>();
            this.Leave_Management_Approval_Matrix1 = new HashSet<Leave_Management_Approval_Matrix>();
            this.Leave_Management_Leave_Allowance = new HashSet<Leave_Management_Leave_Allowance>();
            this.Leave_Management_Leave_Taken = new HashSet<Leave_Management_Leave_Taken>();
            this.Leave_Management_Leave_Taken1 = new HashSet<Leave_Management_Leave_Taken>();
        }
    
        public string pk_user_id { get; set; }
        public string user_firstname { get; set; }
        public string user_lastname { get; set; }
        public string user_name { get; set; }
        public string user_email { get; set; }
        public string user_picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave_Management_Approval_Matrix> Leave_Management_Approval_Matrix { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave_Management_Approval_Matrix> Leave_Management_Approval_Matrix1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave_Management_Leave_Allowance> Leave_Management_Leave_Allowance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave_Management_Leave_Taken> Leave_Management_Leave_Taken { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave_Management_Leave_Taken> Leave_Management_Leave_Taken1 { get; set; }
    }
}
