//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave_Management_Leave_Taken
    {
        public int pk_leave_taken_id { get; set; }
        public string fk_user_id { get; set; }
        public Nullable<int> fk_leave_type { get; set; }
        public Nullable<System.DateTime> leave_days { get; set; }
        public Nullable<bool> is_halfday { get; set; }
        public Nullable<bool> is_afternoon { get; set; }
        public Nullable<int> leave_status { get; set; }
        public string fk_approved_user_id { get; set; }
        public Nullable<System.DateTime> LeaveDateFrom { get; set; }
        public Nullable<System.DateTime> LeaveDateTo { get; set; }
        public Nullable<int> TotalLeave { get; set; }
        public string Remark { get; set; }
    
        public virtual Innovation_Management_User Innovation_Management_User { get; set; }
        public virtual Innovation_Management_User Innovation_Management_User1 { get; set; }
        public virtual Leave_Management_Leave_Type Leave_Management_Leave_Type { get; set; }
    }
}
