//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave_Management_Leave_Allowance
    {
        public int pk_leave_allowance_id { get; set; }
        public string fk_user_id { get; set; }
        public Nullable<int> fk_leave_type_id { get; set; }
        public string allowance_year { get; set; }
        public Nullable<int> allowance_entitlement { get; set; }
        public Nullable<double> allowance_taken { get; set; }
    
        public virtual Innovation_Management_User Innovation_Management_User { get; set; }
        public virtual Leave_Management_Leave_Type Leave_Management_Leave_Type { get; set; }
    }
}
