//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave_Management_Approval_Matrix
    {
        public int pk_approval_id { get; set; }
        public string fk_requestor_id { get; set; }
        public string fk_approver_id { get; set; }
    
        public virtual Innovation_Management_User Innovation_Management_User { get; set; }
        public virtual Innovation_Management_User Innovation_Management_User1 { get; set; }
    }
}
