//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave_Management_Leave_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Leave_Management_Leave_Type()
        {
            this.Leave_Management_Leave_Allowance = new HashSet<Leave_Management_Leave_Allowance>();
            this.Leave_Management_Leave_Taken = new HashSet<Leave_Management_Leave_Taken>();
        }
    
        public int pk_leave_type_id { get; set; }
        public string leave_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave_Management_Leave_Allowance> Leave_Management_Leave_Allowance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave_Management_Leave_Taken> Leave_Management_Leave_Taken { get; set; }
    }
}
