//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PMSEntities : DbContext
    {
        public PMSEntities()
            : base("name=PMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AssignTask> AssignTasks { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<ChangeIssueDetail> ChangeIssueDetails { get; set; }
        public virtual DbSet<ChatMessageDetail> ChatMessageDetails { get; set; }
        public virtual DbSet<ChatPrivateMessageDetail> ChatPrivateMessageDetails { get; set; }
        public virtual DbSet<ChatPrivateMessageMaster> ChatPrivateMessageMasters { get; set; }
        public virtual DbSet<ChatUserDetail> ChatUserDetails { get; set; }
        public virtual DbSet<Expense_tbl> Expense_tbl { get; set; }
        public virtual DbSet<Filedetail> Filedetails { get; set; }
        public virtual DbSet<Innovation_Management_User> Innovation_Management_User { get; set; }
        public virtual DbSet<Leave_Management_Approval_Matrix> Leave_Management_Approval_Matrix { get; set; }
        public virtual DbSet<Leave_Management_Leave_Allowance> Leave_Management_Leave_Allowance { get; set; }
        public virtual DbSet<Leave_Management_Leave_Taken> Leave_Management_Leave_Taken { get; set; }
        public virtual DbSet<Leave_Management_Leave_Type> Leave_Management_Leave_Type { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Tag_tbl> Tag_tbl { get; set; }
        public virtual DbSet<tbl_Task> tbl_Task { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<ProjectMaster> ProjectMasters { get; set; }
    
        public virtual int Update_Chat_Message_IsRead_Status(string fromEmailId, string toEmailId)
        {
            var fromEmailIdParameter = fromEmailId != null ?
                new ObjectParameter("FromEmailId", fromEmailId) :
                new ObjectParameter("FromEmailId", typeof(string));
    
            var toEmailIdParameter = toEmailId != null ?
                new ObjectParameter("ToEmailId", toEmailId) :
                new ObjectParameter("ToEmailId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Chat_Message_IsRead_Status", fromEmailIdParameter, toEmailIdParameter);
        }
    }
}
