//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMaster
    {
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string Projectdescription { get; set; }
        public Nullable<System.DateTime> startingdate { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    }
}
