//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Task
    {
        public int id { get; set; }
        public string TaskId { get; set; }
        public Nullable<int> Status { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public string Createdby { get; set; }
        public string SummaryName { get; set; }
        public Nullable<int> projectid { get; set; }
        public string logintype { get; set; }
        public string devicetype { get; set; }
        public string CreatedTo { get; set; }
    }
}
